### ISSUE TITLE
Support Docker on this fork

### ISSUE THREAD

**Issue by kamikazechaser** [tntwist/binance-trade-bot#15]
I can see that the public docker images referenced in the docker-compose are stale and belong to the parent fork (idkravitz). Do you plan on supporting Docker on this fork? I can send in a PR.

**Comment by tntwist** [comment]
Hi there. It would be awesome if you could provide a PR because im pretty busy with my job atm.

**Comment by lnxd** [comment]
As a temporary workaround @kamikazechaser, you can build this container yourself. 

1. Download the zip and extract it
2. Open terminal and cd to the directory you extracted, run `docker build . -t btb`
3. Replace the instances of `image: idkravitz/binance-trade-bot` with `image: btb` in `docker-compose.yaml`. This tells docker to use your local build, there are two instances in the file as it currently stands.
4. Run `docker compose up`

Much safer than using a build from dockerhub anyway, as unverified dockerhub builds can be modified from the original code and the resulting container has direct API access to your binance account. The downside to doing it this way is that the bot doesn't update automatically when `docker-compose up` is called, but repeating steps 1, 2, and 4 above get around that in a safer manner and can be easily automated with a shell script. 

I think it'd be best to update [README.md](https://github.com/tntwist/binance-trade-bot/blob/master/README.md) with the instructions to create a local build, rather than leading people to use a bunch of unverified builds on dockerhub. I'll make a PR @tntwist.

**Comment by tntwist** [comment]
Thanks for the PR. 🥳
